# Generated by Django 3.2.9 on 2021-11-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('nome', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('especializacao', models.TextField()),
            ],
        ),
    ]
